### PR TITLE
Added new Bottle Rocket palette

### PR DESCRIPTION
**Pull request by aaronbaggett**
Added a simple 5 color palette for Bottle Rocket (BottleRocket2).  I also updated the README.Rmd file to include:
```{r}
wes_palette("BottleRocket2")
```
Should I also add a bottlerocket-1.png to the figure folder?

### CODE REVIEW

**Comment by karthik** [comment]
> Should I also add a bottlerocket-1.png to the figure folder?

Please do, that would be great. Thanks @aaronbaggett

**Comment by aaronbaggett** [comment]
Pushed a new commit at around 11:15AM CST (Update README.Rmd to include BottleRocket2 fig).  Should include bottlerocket-1.png

**Comment by aaronbaggett** [comment]
Hey @karthik, let me know if those pull requests did not come through.  Do I need to close the pull request in order to indicate I'm through making pulls?  Sorry, I'm a bit new to making pull requests.

**Comment by karthik** [comment]
Hi @aaronbaggett 
All good. I'll merge these shortly and add you as a contributor. Thanks very much! :+1:

**Pull request merged**
